version: '3.8'

services:
  # Основная служба PostgreSQL 17.5
  postgresql:
    image: postgres:17.5
    container_name: postgres_db
    restart: unless-stopped
    
    environment:
      # Основные переменные окружения
      POSTGRES_DB: sync_db
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: Password123!
      
      # Дополнительные настройки PostgreSQL
      POSTGRES_INITDB_ARGS: "--encoding=UTF-8 --locale=C"
      
    ports:
      - "5432:5432"
    
    volumes:
      # Постоянное хранение данных
      - postgres_data:/var/lib/postgresql/data
            
      # Скрипты инициализации
      - ./init-scripts:/docker-entrypoint-initdb.d:ro
      
      # Логи PostgreSQL
      - postgres_logs:/var/log/postgresql
    
    # Настройки производительности через команду
    command: >
      postgres
      -c shared_buffers=256MB
      -c effective_cache_size=1GB
      -c work_mem=64MB
      -c maintenance_work_mem=256MB
      -c max_connections=100
      -c wal_buffers=16MB
      -c checkpoint_completion_target=0.9
      -c random_page_cost=1.1
      -c effective_io_concurrency=200
      -c max_parallel_workers=4
      -c max_parallel_workers_per_gather=2
      -c logging_collector=on
      -c log_directory='/var/log/postgresql'
      -c log_filename='postgresql-%Y-%m-%d.log'
      -c log_statement='mod'
      -c log_min_duration_statement=1000
    
    # Проверка здоровья контейнера
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U sync_admin -d distributed_sync"]
      interval: 10s
      timeout: 5s
      retries: 5

# pgAdmin для управления базой
  pgadmin:
    image: dpage/pgadmin4:latest
    container_name: pgadmin_sync
    restart: unless-stopped
    
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@company.local
      PGADMIN_DEFAULT_PASSWORD: Password123!
      PGADMIN_CONFIG_SERVER_MODE: 'False'
    
    ports:
      - "8080:80"
    
    volumes:
      - pgadmin_data:/var/lib/pgadmin
    
    depends_on:
      postgresql:
        condition: service_healthy

# Именованные volumes - Docker создает автоматически
volumes:
  postgres_data:
    driver: local
  pgadmin_data:
    driver: local

networks:
  default:
    name: sync_network
